package com.token.service;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.token.repository.GenerateUserIdManager;

/**
 * User: hitender
 * Date: 11/19/16 12:30 AM
 */
@Service
public class GenerateUserIdService {

    private GenerateUserIdManager generateUserIdManager;

    @Autowired
    public GenerateUserIdService(GenerateUserIdManager generateUserIdManager) {
        this.generateUserIdManager = generateUserIdManager;
    }

    public String getNextAutoGeneratedUserId() {
        return generateUserIdManager.getNextAutoGeneratedUserId();
    }
}
