package com.noqapp.service;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.doThrow;
import static org.mockito.Mockito.when;

import com.noqapp.domain.GenerateUserIds;
import com.noqapp.domain.UserAccountEntity;
import com.noqapp.repository.ForgotRecoverManager;
import com.noqapp.repository.PointEarnedManager;
import com.noqapp.repository.UserAccountManager;
import com.noqapp.repository.UserAuthenticationManager;
import com.noqapp.repository.UserPreferenceManager;
import com.noqapp.repository.UserProfileManager;

import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.data.redis.core.StringRedisTemplate;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.stream.Collectors;

/**
 * User: hitender
 * Date: 11/20/16 5:48 PM
 */
class AccountServiceTest {
    @Mock private UserAccountManager userAccountManager;
    @Mock private UserAuthenticationManager userAuthenticationManager;
    @Mock private UserPreferenceManager userPreferenceManager;
    @Mock private UserProfileManager userProfileManager;
    @Mock private PointEarnedManager pointEarnedManager;
    @Mock private GenerateUserIdService generateUserIdService;
    @Mock private EmailValidateService emailValidateService;
    @Mock private ForgotRecoverManager forgotRecoverManager;
    @Mock private UserAddressService userAddressService;

    private AccountService accountService;

    @Mock UserAccountEntity userAccount;
    @Mock StringRedisTemplate stringRedisTemplate;

    @BeforeEach
    void setup() {
        MockitoAnnotations.openMocks(this);
        accountService = new AccountService(
            userAccountManager,
            userAuthenticationManager,
            userPreferenceManager,
            userProfileManager,
            pointEarnedManager,
            generateUserIdService,
            emailValidateService,
            forgotRecoverManager,
            userAddressService,
            stringRedisTemplate
        );
    }

    @Test
    @DisplayName ("Find When User Does Not Exists")
    void testFindIfUser_Does_Not_Exists() {
        when(userProfileManager.findOneByMail(anyString())).thenReturn(null);
        assertNull(accountService.findByQueueUserId("user_community_3@noqapp.com"));
    }

    @Test
    @DisplayName("Throw data integrity violation exception when version number is different")
    void failed_to_save_userAccount_with_dataIntegrityViolationException() {
        when(userAccount.getQueueUserId()).thenReturn("test_id");
        doThrow(DataIntegrityViolationException.class).when(userAccountManager).save(userAccount);
        Throwable exception = assertThrows(DataIntegrityViolationException.class,
                ()-> accountService.save(userAccount));
        assertNull(exception.getMessage(), "No message is set when data integrity violation happens");
    }

    @Test
    void validatePopFromList() {
        Collection<String> filteredCollection = null;
        String qid;
        String elements = "[100000028449, 100000031739]"
            .replaceAll("\\[", "")
            .replaceAll("\\]", "")
            .replaceAll(" ", "");
        String[] a = elements.split(",");
        List<String> missingQids = Arrays.asList(a);
        if (missingQids.isEmpty() || missingQids.contains(String.valueOf(GenerateUserIds.STARTING_USER_ID))) {
            qid = generateUserIdService.getNextAutoGeneratedUserId();
        } else {
            qid = missingQids.iterator().next();
            filteredCollection = missingQids.stream().filter(e -> !e.equalsIgnoreCase(qid)).collect(Collectors.toList());
        }

        assertNotNull(filteredCollection);
        assertEquals(filteredCollection.iterator().next(), "100000031739");
    }
}
