package com.token.repository;

import com.token.domain.GenerateUserIds;

/**
 * User: hitender
 * Date: 11/19/16 12:31 AM
 */
public interface GenerateUserIdManager extends RepositoryManager<GenerateUserIds> {

    String getNextAutoGeneratedUserId();

    long getLastGenerateUserId();
}